version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.11

jobs:
  lint-go:
    docker: &docker_go
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go get golang.org/x/lint/golint
      - run: golint -set_exit_status ./...

  test-go:
    docker: *docker_go
    steps:
      - checkout
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p /tmp/test-results
      - run: go test -v ./... | go-junit-report > /tmp/test-results/spec.xml
      - store_test_results:
          path: /tmp/test-results

  vet-go:
    docker: *docker_go
    steps:
      - checkout
      - run: go vet ./...

  build-go:
    executor: go
    steps:
      - checkout
      - attach_workspace: &attach_workspace
          at: .
      - run: make build
      - persist_to_workspace:
          root: .
          paths:
            - bin

workflows:
  version: 2
  go:
    jobs:
      - lint-go: &go_job
          filters: &filters_all
            tags:
              only: /.*?/
      - test-go: *go_job
      - vet-go: *go_job

      - build-go:
          requires: [lint-go, test-go, vet-go]
          filters: &filters_tags
            branches:
              ignore: /.*?/
            tags:
              only: /^v/
