version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.13

jobs:
  test:
    executor: go
    steps:
      - run: go get golang.org/x/lint/golint
      - checkout
      - run: ./test

  build:
    executor: go
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: VERSION=$CIRCLE_TAG make build
      - persist_to_workspace:
          root: .
          paths:
            - out

  deploy:
    docker:
      - image: circleci/python:3.6
        environment:
          BINARY: igniter-shell
          BUCKET: public.gameye.com
    steps:
      - attach_workspace:
          at: .
      - run: sudo pip install awscli
      - run: >
          aws s3 cp
          out/
          s3://$BUCKET/binaries/$BINARY/$CIRCLE_TAG/
          --recursive

workflows:
  version: 2
  go:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - build:
          filters:
            tags:
              only: /.*/

      - deploy:
          context: aws-authorized
          requires: [test, build]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*$/
